# Travis Continuous Integration Configuration File, based on ..
#   Generic MoveIt Travis Continuous Integration Configuration File
#   Works with all MoveIt! repositories/branches
#   Author: Dave Coleman, Jonathan Bohren
language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
env:
  - ROS_DISTRO=groovy ROSWS=rosws  BUILDER=rosbuild  USE_DEB=true  EXTRA_DEB=ros-groovy-navigation
  - ROS_DISTRO=groovy ROSWS=rosws  BUILDER=rosbuild  USE_DEB=false EXTRA_DEB=ros-groovy-navigation
  - ROS_DISTRO=groovy ROSWS=wstool BUILDER=catkin    USE_DEB=true  EXTRA_DEB=ros-groovy-navigation
  - ROS_DISTRO=groovy ROSWS=wstool BUILDER=catkin    USE_DEB=false EXTRA_DEB="ros-groovy-navigation"
  - ROS_DISTRO=hydro  ROSWS=wstool BUILDER=catkin    USE_DEB=true
  - ROS_DISTRO=hydro  ROSWS=wstool BUILDER=catkin    USE_DEB=false
  - TEST_TYPE=work_with_downstream  TEST_PACKAGE=hironx-ros-bridge ROS_DISTRO=hydro EXTRA_DEB="ros-hydro-roslint ros-hydro-robot-pose-ekf"
  - TEST_TYPE=work_with_315_1_10    TEST_PACKAGE=hironx-ros-bridge ROS_DISTRO=hydro EXTRA_DEB=ros-hydro-roslint
matrix:
  allow_failures:
  - env: ROS_DISTRO=groovy ROSWS=rosws  BUILDER=rosbuild  USE_DEB=false
  - env: ROS_DISTRO=groovy ROSWS=wstool BUILDER=catkin    USE_DEB=false
notifications:
  email:
    recipients:
      - k-okada@jsk.t.u-tokyo.ac.jp
      - iisaito@opensource-robotics.tokyo.jp
    on_success: always #[always|never|change] # default: change
    on_failure: always #[always|never|change] # default: always
script:
  - export ROS_PARALLEL_JOBS="-j4 -l4"
  - if [ "${TEST_TYPE}" == "" ] ; then source .travis/travis.sh; else source ./.travis_test.sh ; fi
