# Travis Continuous Integration Configuration File, based on ..
#   Generic MoveIt Travis Continuous Integration Configuration File
#   Works with all MoveIt! repositories/branches
#   Author: Dave Coleman, Jonathan Bohren
sudo: required
dist: trusty
language: c++
cache:
  - ccache
  - apt
env:
  global:
    - ROSWS=wstool
    - BUILDER=catkin
    - CATKIN_PARALLEL_JOBS='-p2'
    - CATKIN_PARALLEL_TEST_JOBS='-p1'
    - ROS_PARALLEL_TEST_JOBS='-j1'
    - secure: "QxLoOR83QHxGdMJ3BJ0TwRJdezWZaiWfoe4O88XMSG8LFMZLRbqNmOsrLn9b/VgMQpz44CP7tXXQvNz0FDRSTpgSdyNT+p1UA7iEhFYI4G3OEsYf0r6/4rjvtM7FCoIsBiPYBwofVAUP+U9d8Scjn+2+xjjKwOpEbaE/yc+zwrc="
  matrix:
    - USE_JENKINS=true ROS_DISTRO=hydro  USE_DEB=true
    - USE_JENKINS=true ROS_DISTRO=hydro  USE_DEB=false   NOT_TEST_INSTALL=true
    - USE_JENKINS=true ROS_DISTRO=hydro  USE_DEB=source  NOT_TEST_INSTALL=true EXTRA_DEB="ros-hydro-roseus ros-hydro-euscollada ros-hydro-pr2eus" ROS_PARALLEL_JOBS="-j1 -l1" IS_EUSLISP_TRAVIS_TEST="true"
    - USE_JENKINS=true ROS_DISTRO=hydro  USE_DEB=true    NOT_TEST_INSTALL=true INSTALL_SRC="http://github.com/start-jsk/rtmros_tutorials" TEST_PKGS="hrpsys_ros_bridge_tutorials" INSTALL_SRC_SECURE="git@github.com:start-jsk/rtmros_hrp2" TEST_PKGS_SECURE="jsk_hrp2_ros_bridge"
    - USE_JENKINS=true ROS_DISTRO=hydro  USE_DEB=source  NOT_TEST_INSTALL=true
    - USE_JENKINS=true ROS_DISTRO=hydro  USE_DEB=true    EXTRA_DEB="ros-hydro-hrpsys-ros-bridge ros-hydro-pr2eus" ROS_PARALLEL_JOBS="-j1 -l1" NOT_TEST_INSTALL=true IS_EUSLISP_TRAVIS_TEST="true"
    - USE_JENKINS=true ROS_DISTRO=hydro  USE_DEB=false   EXTRA_DEB="ros-hydro-hrpsys-ros-bridge ros-hydro-pr2eus" ROS_PARALLEL_JOBS="-j1 -l1" NOT_TEST_INSTALL=true IS_EUSLISP_TRAVIS_TEST="true"
    - USE_TRAVIS=true ROS_DISTRO=indigo USE_DEB=true
    - USE_TRAVIS=true ROS_DISTRO=indigo USE_DEB=false   NOT_TEST_INSTALL=true
    - USE_TRAVIS=true ROS_DISTRO=indigo USE_DEB=true    EXTRA_DEB="ros-indigo-hrpsys-ros-bridge ros-indigo-pr2eus" CATKIN_PARALLEL_JOBS='-p4' NOT_TEST_INSTALL=true IS_EUSLISP_TRAVIS_TEST="true"
    - USE_JENKINS=true ROS_DISTRO=indigo USE_DEB=false   EXTRA_DEB="ros-indigo-hrpsys-ros-bridge ros-indigo-pr2eus" ROS_PARALLEL_JOBS="-j1 -l1" NOT_TEST_INSTALL=true IS_EUSLISP_TRAVIS_TEST="true"
    - USE_TRAVIS=true ROS_DISTRO=jade   USE_DEB=true
    - USE_JENKINS=true ROS_DISTRO=kinetic USE_DEB=true
    - USE_TRAVIS=true TEST_TYPE=work_with_downstream  TEST_PACKAGE=hironx-ros-bridge ROS_DISTRO=indigo EXTRA_DEB="ros-indigo-roslint"
    - USE_TRAVIS=true TEST_TYPE=work_with_315_1_10    TEST_PACKAGE=hironx-ros-bridge ROS_DISTRO=indigo EXTRA_DEB="ros-indigo-roslint"
    - USE_TRAVIS=true TEST_TYPE=work_with_downstream  TEST_PACKAGE=hironx-ros-bridge ROS_DISTRO=jade EXTRA_DEB="ros-jade-roslint"
    - USE_TRAVIS=true TEST_TYPE=work_with_315_1_10    TEST_PACKAGE=hironx-ros-bridge ROS_DISTRO=jade EXTRA_DEB="ros-jade-roslint"
    - USE_JENKINS=true ROS_DISTRO=hydro  USE_DEB=true  EXTRA_DEB="ros-hydro-pr2eus"
matrix:
  allow_failures:
  - env: USE_TRAVIS=true ROS_DISTRO=indigo USE_DEB=true    EXTRA_DEB="ros-indigo-hrpsys-ros-bridge ros-indigo-pr2eus" CATKIN_PARALLEL_JOBS='-p4' NOT_TEST_INSTALL=true IS_EUSLISP_TRAVIS_TEST="true"
  - env: USE_JENKINS=true ROS_DISTRO=kinetic USE_DEB=true
  - env: USE_TRAVIS=true TEST_TYPE=work_with_downstream  TEST_PACKAGE=hironx-ros-bridge ROS_DISTRO=jade EXTRA_DEB="ros-jade-roslint"
  - env: USE_TRAVIS=true TEST_TYPE=work_with_315_1_10    TEST_PACKAGE=hironx-ros-bridge ROS_DISTRO=jade EXTRA_DEB="ros-jade-roslint"
notifications:
  email:
    recipients:
      - k-okada@jsk.t.u-tokyo.ac.jp
      - iisaito@opensource-robotics.tokyo.jp
    on_success: always #[always|never|change] # default: change
    on_failure: always #[always|never|change] # default: always
before_script:
  - set -x
  - if [ "${TRAVIS_SECURE_ENV_VARS}" == "true" ]; then openssl aes-256-cbc -K $encrypted_b79fc5843df3_key -iv $encrypted_b79fc5843df3_iv -in .secrets.tar.enc -out .secrets.tar -d; tar -C ~/ -xvf .secrets.tar; export INSTALL_SRC="$INSTALL_SRC $INSTALL_SRC_SECURE"; export TEST_PKGS="$TEST_PKGS $TEST_PKGS_SECURE"; fi
  - export REPOSITORY_NAME=`basename $PWD`
  - if [ "${INSTALL_SRC}" != "" ] ;then export sudo apt-get install python-yaml; export BEFORE_SCRIPT="$(for src in $INSTALL_SRC; do name=`basename $src`; echo "python -c \"import yaml;print yaml.dump([{\\\"git\\\":{\\\"uri\\\":\\\"$src\\\",\\\"local-name\\\":\\\"$name\\\"}}], default_flow_style=False)\" >> .rosinstall;"; done)ls -al; cat .rosinstall; wstool update"; export USE_DEB=false; fi; # set USE_DEB false to enable .travis.rosinstall
script:
  - if [ "${IS_EUSLISP_TRAVIS_TEST}" != "true" ] ; then export ROS_PARALLEL_JOBS="-j2 -l2" ; fi
  - if [ "${ROS_DISTRO}" == "hydro" ] ; then sudo apt-get install -y --force-yes gdebi && wget https://bintray.com/artifact/download/furushchev/ros-shadow-fixed/python-catkin-tools_0.3.1-1_all.deb && wget https://bintray.com/artifact/download/furushchev/ros-shadow-fixed/python-catkin-pkg_0.2.10-1_all.deb && sudo gdebi -n -q python-catkin-pkg_0.2.10-1_all.deb && sudo gdebi -n -q python-catkin-tools_0.3.1-1_all.deb && sudo apt-mark hold python-catkin-tools; fi
  - if [ "${TEST_TYPE}" == "" ] ; then source .travis/travis.sh; else source ./.travis_test.sh ; fi
  - ccache -s
after_success:
  - TRAVIS_JOB_SUBNUMBER="${TRAVIS_JOB_NUMBER##*.}"
  - if [ "$TRAVIS_JOB_SUBNUMBER" == 9 -a "$TRAVIS_BRANCH" == "master" -a "${TRAVIS_SECURE_ENV_VARS}" == "true" ]; then ${CI_SOURCE_PATH}/.travis/upload-docs.sh; fi
